apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test3-z2y6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test3-z2y6
    app.kubernetes.io/part-of: my-test3-2
  name: my-test3-z2y6
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: my-test3-z2y6
status:
  loadBalancer: {}
